import { useRecoilValue } from 'recoil'
import { solanaCluster } from '../../app/store'
import { userProfile } from '../../me/store'

export * from './coinPrice'
export * from './currencyToken'
export * from './fetchAccountDetails'
export * from './fetchAccountHistory'
export * from './fetchAccountInfo'
export * from './fetchBlock'
export * from './fetchCoinGecko'
export * from './fetchEpoch'
export * from './fetchLargestAccounts'
export * from './fetchNFTDetails'
export * from './fetchNftTransactionsOnchain'
export * from './fetchParsedTokenAccountsByOwner'
export * from './fetchSignaturesForAddress'
export * from './fetchSlot'
export * from './fetchStakeActivation'
export * from './fetchTokenRegistry'
export * from './fetchTransaction'
export * from './fetchTransactionStatus'
export * from './fetchUserDomains'
export * from './fetchVerifiableBuilds'
export * from './pageIdx'

export const useSolanaCluster = () => useRecoilValue(solanaCluster)
export const useUserProfile = () => useRecoilValue(userProfile)
