import OpenSearchCollectionSourceType from './OpenSearchCollectionSourceType'
import type OpenSearchSourceHighlightType from './OpenSearchSourceHighlightType'

type OpenSearchCollectionSourceHighlightType =
  OpenSearchSourceHighlightType<OpenSearchCollectionSourceType>

export default OpenSearchCollectionSourceHighlightType
